# .github/workflows/keep_streamlit_awake.yml
name: Keep Streamlit App Awake

on:
  schedule:
    - cron: "*/10 * * * *"  # every 10 mins
  workflow_dispatch:

jobs:
  ping-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Playwright
        run: |
          npm install -D playwright
          npx playwright install
      - name: Ping Streamlit App with Playwright
        run: |
          echo "const { chromium } = require('playwright'); (async () => {
            const browser = await chromium.launch();
            const page = await browser.newPage();
            await page.goto('https://cookdoor.streamlit.app/', { waitUntil: 'load' });
            await page.waitForTimeout(5000); // Wait to simulate usage
            await browser.close();
          })();" > ping.js
          node ping.js
