name: Keep cookdoor Alive

on:
  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Run Puppeteer Script
        run: |
          echo "const puppeteer = require('puppeteer');

          (async () => {
            const browser = await puppeteer.launch({
              headless: true,
              args: ['--no-sandbox', '--disable-setuid-sandbox']
            });
            const page = await browser.newPage();
            await page.goto('https://cookdoor.streamlit.app/', {
              waitUntil: 'networkidle2'
            });
            await page.waitForTimeout(15000); // 15 seconds
            await browser.close();
          })();" > script.js

          node script.js
